version: '3.3'

services:
  pgsql:
    image: postgres:10
    container_name: 'postgres'
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./.database/pgsql_10:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: excellparser
      POSTGRES_USER: excellparser